project:
  type: website
  output-dir: docs

website:
  title: "Dahham Alsoud"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: publications.qmd
      - href: cv-dahhamalsoud.qmd
      - href: software.qmd

format:
  html:
    page-layout: full
    theme: United
    css: styles.css
    toc: true
    grid: 
      margin-width: 400px
      body-width: 900px

editor: visual

